import {
    useMultiFileAuthState,
    DisconnectReason,
    proto,
    makeInMemoryStore,
    makeCacheableSignalKeyStore,
    getAggregateVotesInPollMessage,
    WASocket,
    BaileysEventMap,
    AnyMediaMessageContent,
    AnyMessageContent,
    PollMessageOptions,
    downloadMediaMessage,
    WAMessage,
    MessageUpsertType,
    isJidGroup,
    isJidBroadcast,
} from '@builderbot/core-baileys'

const makeWASocketOther = require('@builderbot/core-baileys').default

export {
    makeWASocketOther,
    useMultiFileAuthState,
    DisconnectReason,
    proto,
    makeInMemoryStore,
    makeCacheableSignalKeyStore,
    getAggregateVotesInPollMessage,
    WASocket,
    BaileysEventMap,
    AnyMediaMessageContent,
    AnyMessageContent,
    PollMessageOptions,
    downloadMediaMessage,
    WAMessage,
    MessageUpsertType,
    isJidGroup,
    isJidBroadcast,
}
